spring.application.name=QueriesTask
spring.profiles.active=local
server.port=${PORT}

#POSTGRES: QUERY STORAGE DB
app.datasource.postgres.jdbc-url=${POSTGRES_DATASOURCE_URL}
app.datasource.postgres.username=${POSTGRES_DATASOURCE_USERNAME}
app.datasource.postgres.password=${POSTGRES_DATASOURCE_PASSWORD}
app.datasource.postgres.driver-class-name=org.postgresql.Driver

app.datasource.postgres.maximum-pool-size=20
app.datasource.postgres.minimum-idle=5
app.datasource.postgres.connection-timeout=30000
app.datasource.postgres.pool-name=PostgresHikariPool

#CLICKHOUSE: DATA FOR ANALYTICS DB
#make sure that the datasource has readonly=1 parameter
app.datasource.clickhouse.jdbc-url=${CLICKHOUSE_DATASOURCE_URL} 
app.datasource.clickhouse.username=${CLICKHOUSE_DATASOURCE_USERNAME}
app.datasource.clickhouse.password=${CLICKHOUSE_DATASOURCE_PASSWORD}
app.datasource.clickhouse.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver

app.datasource.clickhouse.maximum-pool-size=5
app.datasource.clickhouse.minimum-idle=2
app.datasource.clickhouse.connection-timeout=60000
app.datasource.clickhouse.pool-name=ClickHouseHikariPool
